"use client";

import { useState, useEffect, useCallback } from "react";
import Link from "next/link";

interface CustomerDetail {
  order_id: string;
  customer_name: string;
  customer_phone: string;
  qty: number;
  unit: string;
}

interface PurchaseItem {
  veg_id: string;
  name_en: string;
  name_ta: string;
  unit: string;
  category: string;
  total_qty: number;
  customers: CustomerDetail[];
}

export default function AdminPurchaseListPage() {
  const [purchaseList, setPurchaseList] = useState<PurchaseItem[]>([]);
  const [totalOrders, setTotalOrders] = useState(0);
  const [deliveryDate, setDeliveryDate] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const loadPurchaseList = useCallback(() => {
    setLoading(true);
    setError(null);
    fetch("/api/admin/purchase-list")
      .then((r) => {
        if (!r.ok) throw new Error("Failed to load purchase list");
        return r.json();
      })
      .then((d) => {
        setPurchaseList(d.purchase_list ?? []);
        setTotalOrders(d.total_orders ?? 0);
        setDeliveryDate(d.delivery_date ?? "");
      })
      .catch((err) => setError(err.message ?? "Failed to load purchase list"))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    loadPurchaseList();
  }, [loadPurchaseList]);

  const handleCopyWhatsApp = async () => {
    if (purchaseList.length === 0) return;

    let text = `*PPR WHOLESALE PURCHASE LIST*\nDelivery Date: ${deliveryDate}\nTotal Orders: ${totalOrders}\n-----------------------------------\n\n`;

    purchaseList.forEach((item, idx) => {
      text += `${idx + 1}. *${item.name_en}* (${item.name_ta}) — *${item.total_qty} ${item.unit}*\n`;
      item.customers.forEach((c) => {
        text += `   • ${c.customer_name} (${c.customer_phone}): ${c.qty} ${c.unit}\n`;
      });
      text += `\n`;
    });

    text += `-----------------------------------\nGenerated by PPR Admin System`;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 3000);
    } catch {
      setError("Failed to copy to clipboard. Please copy manually.");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div style={{ padding: "40px 24px", textAlign: "center", color: "#6b7280", fontFamily: "var(--font)" }}>
        Loading wholesale purchase list…
      </div>
    );
  }

  const dateFormatted = deliveryDate
    ? new Date(deliveryDate).toLocaleDateString("en-IN", {
        weekday: "long",
        day: "numeric",
        month: "short",
        year: "numeric",
      })
    : "";

  return (
    <div className="page-content" style={{ padding: "16px", maxWidth: "768px", margin: "0 auto", fontFamily: "var(--font)" }}>
      {/* Print styles */}
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { background: #fff; }
          .page-content { padding: 0 !important; max-width: 100% !important; }
          .purchase-card { border: 1px solid #ccc !important; box-shadow: none !important; page-break-inside: avoid; }
        }
      `}</style>

      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "20px" }}>
        <div>
          <Link href="/manage/stock" className="no-print" style={{ fontSize: "0.8rem", color: "#6b7280", textDecoration: "none" }}>
            ← Admin Dashboard
          </Link>
          <h1 style={{ fontSize: "1.35rem", fontWeight: 700, marginTop: "4px", color: "var(--text-primary)", display: "flex", alignItems: "center", gap: "8px" }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#166534" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="9" cy="21" r="1" />
              <circle cx="20" cy="21" r="1" />
              <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
            </svg>
            Purchase List
          </h1>
          <p style={{ fontSize: "0.82rem", color: "#6b7280" }}>
            For delivery: <strong>{dateFormatted}</strong>
          </p>
        </div>
        <div style={{ textAlign: "right" }}>
          <span
            style={{
              background: "#166534",
              color: "#fff",
              borderRadius: "9999px",
              padding: "4px 12px",
              fontSize: "0.8rem",
              fontWeight: 700,
              display: "inline-block",
            }}
          >
            {totalOrders} active order{totalOrders !== 1 ? "s" : ""}
          </span>
          <p style={{ fontSize: "0.72rem", color: "#6b7280", marginTop: "4px" }}>
            {purchaseList.length} total item type{purchaseList.length !== 1 ? "s" : ""}
          </p>
        </div>
      </div>

      {/* Action buttons */}
      <div className="no-print" style={{ display: "flex", gap: "10px", marginBottom: "20px" }}>
        <button
          onClick={handleCopyWhatsApp}
          disabled={purchaseList.length === 0}
          style={{
            flex: 1,
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "8px",
            background: copied ? "#059669" : "#166534",
            color: "#fff",
            border: "none",
            borderRadius: "12px",
            padding: "12px 16px",
            fontWeight: 700,
            fontSize: "0.88rem",
            cursor: "pointer",
            transition: "background 150ms",
          }}
        >
          {copied ? (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12" />
              </svg>
              Copied to Clipboard!
            </>
          ) : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
              </svg>
              Copy List for WhatsApp
            </>
          )}
        </button>
        <button
          onClick={handlePrint}
          disabled={purchaseList.length === 0}
          style={{
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            gap: "6px",
            background: "#fff",
            color: "#374151",
            border: "1.5px solid #d1d5db",
            borderRadius: "12px",
            padding: "12px 18px",
            fontWeight: 700,
            fontSize: "0.88rem",
            cursor: "pointer",
          }}
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          Print
        </button>
      </div>

      {error && (
        <div
          style={{
            background: "#fef2f2",
            border: "1.5px solid #fecaca",
            borderRadius: "12px",
            padding: "14px 16px",
            marginBottom: "20px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <p style={{ fontSize: "0.85rem", color: "#dc2626", fontWeight: 500 }}>{error}</p>
          <button
            onClick={loadPurchaseList}
            style={{
              padding: "6px 14px",
              background: "#dc2626",
              color: "#fff",
              border: "none",
              borderRadius: "8px",
              fontSize: "0.78rem",
              fontWeight: 700,
              cursor: "pointer",
            }}
          >
            Retry
          </button>
        </div>
      )}

      {purchaseList.length === 0 ? (
        <div
          style={{
            background: "#fff",
            borderRadius: "16px",
            padding: "40px 20px",
            textAlign: "center",
            border: "1.5px solid #e5e7eb",
          }}
        >
          <div style={{ display: "flex", justifyContent: "center", marginBottom: "12px", color: "#9ca3af" }}>
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="9" cy="21" r="1" />
              <circle cx="20" cy="21" r="1" />
              <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" />
            </svg>
          </div>

          <h2 style={{ fontSize: "1.1rem", fontWeight: 700, color: "var(--text-primary)" }}>
            No Active Orders for Tomorrow
          </h2>
          <p style={{ fontSize: "0.85rem", color: "#6b7280", marginTop: "4px" }}>
            When customers place orders, the aggregated total quantities to purchase will automatically appear here.
          </p>
        </div>
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
          {purchaseList.map((item) => (
            <div
              key={item.veg_id}
              className="purchase-card"
              style={{
                background: "#ffffff",
                borderRadius: "16px",
                padding: "16px 18px",
                border: "1.5px solid #e5e7eb",
                boxShadow: "0 2px 8px rgba(0,0,0,0.03)",
              }}
            >
              {/* Item Header — English & Tamil name + Total Quantity */}
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "12px" }}>
                <div>
                  <h3 style={{ fontSize: "1.05rem", fontWeight: 700, color: "#111827", lineHeight: 1.2 }}>
                    {item.name_en}
                  </h3>
                  {item.name_ta && (
                    <p style={{ fontSize: "0.85rem", color: "#166534", fontWeight: 600, marginTop: "2px" }}>
                      {item.name_ta}
                    </p>
                  )}
                </div>
                <div
                  style={{
                    background: "#f0fdf4",
                    border: "1.5px solid #bbf7d0",
                    borderRadius: "12px",
                    padding: "6px 14px",
                    textAlign: "right",
                  }}
                >
                  <span style={{ fontSize: "0.72rem", textTransform: "uppercase", color: "#166534", fontWeight: 700, display: "block" }}>
                    Total Needed
                  </span>
                  <span style={{ fontSize: "1.15rem", fontWeight: 800, color: "#15803d" }}>
                    {item.total_qty} {item.unit}
                  </span>
                </div>
              </div>

              {/* Customer Breakdown Section */}
              <div style={{ borderTop: "1px solid #f3f4f6", paddingTop: "10px" }}>
                <p style={{ fontSize: "0.75rem", fontWeight: 700, color: "#6b7280", textTransform: "uppercase", letterSpacing: "0.04em", marginBottom: "8px" }}>
                  Ordered By ({item.customers.length} customer{item.customers.length !== 1 ? "s" : ""}):
                </p>
                <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                  {item.customers.map((c, i) => (
                    <div
                      key={`${c.order_id}-${i}`}
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        fontSize: "0.85rem",
                        background: "#f9fafb",
                        padding: "8px 12px",
                        borderRadius: "8px",
                        border: "1px solid #f3f4f6",
                      }}
                    >
                      <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                        <span style={{ fontWeight: 600, color: "#1f2937" }}>{c.customer_name}</span>
                        {c.customer_phone && (
                          <span style={{ color: "#6b7280", fontSize: "0.78rem" }}>
                            ({c.customer_phone})
                          </span>
                        )}
                      </div>
                      <span style={{ fontWeight: 700, color: "#166534" }}>
                        {c.qty} {c.unit}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
